Set up todo
Kandy-Peter/to-do-list pull request #1
Opened 2022-01-12 16:44 UTC by Kandy-Peter

This pull request has the following contents and steps:

- I installed Webpack and its dependencies
- create the todo list template using HTML/CSS/javascript
- display todo list tasks from javascript using array and object  in javascript
- install linters and fix errors.

2022-01-12 17:24 UTC, leolpaz requested changes
Hi @Kandy-Peter , 

You've done an amazing job so far, I'd like to highlight the following:
- Good job setting up webpack

Some issues need to be resolved before your approval, but you're almost there!

<img src="https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 17:24 UTC, leolpaz commented on src/index.js
> +}
- [ ] To comply with the requirement screenshotted below kindly add something either here or above it that sorts the array before rendering them on the page so they show in order based on their index(id) number
![image](https://user-images.githubusercontent.com/73140461/149189539-76984da6-243c-4572-be1d-d30fd12359a5.png)

2022-01-12 18:15 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Kandy, 
 ### You have been doing a tremendous job so far :ok_hand:

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-12 18:15 UTC, SajjadAhmad14 commented on src/index.js
> +const newTodoArray = todoObjectArray;
Please make sure the tasks are rendered on screen in the order of their index values as it's asked to implement by previous code reviewer.

2022-01-13 06:33 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @Kandy-Peter ,  

Your project is complete!  it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 
You have done a great job!

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 06:37 UTC, merged